site_name: MOSAIC Satellite

theme: 
  name: material
  logo: 'images/MOSAIC_logo_nob.png'
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - header.autohide
    - navigation.path
    - content.code.copy
    - content.code.select
    - navigation.top
  palette:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search  # To have search functionality on the document
  - mkdocs-pdf #PDF Embed Ability

markdown_extensions:
  - attr_list
  - md_in_html
  - attr_list
  - abbr
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.pathconverter:
      base_path: 'DOCUMENTATION' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'

nav: # Setting up the navigation. The below list will be tabs on left panel
  - Home: 
    - Welcome: index.md
    - Overview: overview/index.md
    - Getting Your Own MOSAIC: getting_mosaic/index.md
    - Quick Start Guide: quick_start/index.md
    - Core Documentation: core_documentation/index.md
    - Contact: contact/index.md
  - Overview:
    - Overview: overview/index.md
    - Design Philosophy: overview/design_philosophy.md
    - MOSAIC Elements: overview/mosaic_elements.md
    - Publications: overview/publications.md
  - Getting Your Own MOSAIC: 
    - Getting MOSAIC: getting_mosaic/index.md
    - Self-Assembly: 
      - Overview: getting_mosaic/self_assemble/overview.md
      - Step 1 - Fabricate Boards: getting_mosaic/self_assemble/fabricate_boards.md
      - Step 2 - Purchase Components: getting_mosaic/self_assemble/purchase_components.md
      - Step 3 - Assemble Boards: getting_mosaic/self_assemble/assemble_boards.md
      - Step 4 - Print Frame: getting_mosaic/self_assemble/print_frame.md
      - What's Next?: getting_mosaic/self_assemble/whats_next.md
  - Quick-Start Guide:
    - Introduction: quick_start/index.md
    - Suggested Reading: quick_start/suggested_reading.md
    - Getting Started with MOSAIC: 
      - Overview: quick_start/getting_started/overview.md
      - Step 1 - Choose Components: quick_start/getting_started/choose_components.md
      - Step 2 - Hookup Guide: quick_start/getting_started/hookup_guide.md
      - Step 3 - Software Setup: quick_start/getting_started/software_setup.md
      - Step 4 - Hardware Assembly: quick_start/getting_started/hardware_assembly.md
    - Become a Contributor: quick_start/become_contributor.md
  - Core Documentation:
    - core_documentation/index.md
    - Quick Reference: core_documentation/quick_reference.md
    - Hardware: 
      - Overview: core_documentation/hardware/index.md
      - Main Board: 
        - Overview: core_documentation/hardware/main_board/index.md
        - Processors: core_documentation/hardware/main_board/processors.md
        - Function Boards: core_documentation/hardware/main_board/function_boards.md
        - Memory Modules: core_documentation/hardware/main_board/memory_modules.md
        - Change Log: core_documentation/hardware/main_board/change_log.md
      - Power Board: 
        - Overview: core_documentation/hardware/power_board/index.md
        - Change Log: core_documentation/hardware/power_board/change_log.md
      - ProtoBoard:
        - Overview: core_documentation/hardware/protoboard/index.md
        - Change Log: core_documentation/hardware/protoboard/change_log.md
      - Frame: 
        - Overview: core_documentation/hardware/frame/index.md
        - Change Log: core_documentation/hardware/frame/change_log.md
      - Sensors and Radios: core_documentation/hardware/sensors_and_radios.md
    - Software:
      - Overview: core_documentation/software/index.md
    - Troubleshooting:
      - Overview: core_documentation/troubleshooting/index.md
  - Contact: 
    - Contact: contact/index.md

extra:
  social:
    - icon: material/github 
      link: https://github.com/MOSAIC-Satellite
